sudo: false
language: python
virtualenv:
  system_site_packages: true
services:
  - postgresql
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="false"
addons:
  apt:
    packages:
      - git
      - python-pip
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
before_script:
  - git config --global user.email "w.usher@ucl.ac.uk"
  - git config --global user.name "Will Usher"
  - psql -U postgres -c "CREATE EXTENSION postgis"
  - psql -c 'CREATE DATAGASE test_aisdb;' -U postgres
  - psql -U postgres -c "CREATE USER test_ais WITH PASSWORD 'test_ais' SUPERUSER;"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE test_aisdb TO test_ais;"
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
notifications:
  email: false
